name: Configure machine

on:
  push:
    branches:
    - main
jobs:

  configure_host:
    runs-on: ubuntu-latest
    name: Install packages
    environment:
      name: PACKER
      url: ${{ steps.step_name.outputs.url_output }}
    steps:
    - name: set envs
      run: env
      env:
        TEST_SECRET: ${{ secrets.TEST_SECRET }}
    - name: print envs
      run: env