name: Configure machine

on:
  push:
    branches:
    - main
jobs:

  configure_host:
    runs-on: ubuntu-latest
    name: Install packages
    environment:
      name: PACKER
      url: ${{ steps.step_name.outputs.url_output }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run shell script
      run: bash configure_machine.sh -xe
    - name: Run packer templates
      run: bash run_packer.sh -xe
      env:
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}