name: Configure machine

on:
  push:
    branches:
    - main
jobs:

  configure_host:
    runs-on: ubuntu-latest
    name: Install packages
    environment:
      name: PACKER
    steps:
    - name: set envs
      env:
        TEST_SECRET: ${{ secrets.TEST_SECRET }}
      run: env
    - name: print envs
      run: env