name: Configure machine

on:
  push:
    branches:
    - main
jobs:

  configure_host:
    runs-on: ubuntu-latest
    name: Install packages
    environment:
      name: PACKER
    steps:
    - name: Print envs
      run: env